stages:
  - dependencies
  - test
  - build

cache:
  paths:
    - node_modules/

Install:
  stage: dependencies
  image: node:12.16.3-alpine
  script:
    - npm install
  only:
    - develop
    - staging
  except:
    changes:
      - client/*
  artifacts:
    paths:
      - node_modules/

MR_Install:
  stage: dependencies
  image: node:12.16.3-alpine
  script:
    - npm install
  only:
    - merge_requests
  tags:
    - merge
  except:
    changes:
      - client/*
  artifacts:
    paths:
      - node_modules/

Test:
  stage: test
  image: node:12.16.3-alpine
  only:
    - develop
    - staging
  except:
    changes:
      - client/*
  script: npm run test

MR_Test:
  stage: test
  image: node:12.16.3-alpine
  only:
    - merge_requests
  tags:
    - merge
  except:
    changes:
      - client/*
  script: npm run test

Build Develop Image:
  stage: build
  image: docker:18
  services:
    - docker:dind
  only:
    - develop
  except:
    changes:
      - client/*
  cache:
    paths:
      - node_modules/
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/app:develop || true
    - >
      docker build
      --pull
      --build-arg VCS_REF=develop
      --build-arg VCS_URL=$CI_PROJECT_URL
      --cache-from $CI_REGISTRY_IMAGE/app:develop
      --tag $CI_REGISTRY_IMAGE/app:develop
      .
    - docker push $CI_REGISTRY_IMAGE/app:develop
# Staging build:
#   stage: build
#   image: docker:18
#   services:
#     - docker:dind
#   only:
#     - staging
#   except:
#     changes:
#       - client/*
#   cache:
#     paths:
#       - node_modules/
#   before_script:
#     - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
#     - docker info
#   script:
#     - docker pull $CI_REGISTRY_IMAGE/app:staging || true
#     - >
#       docker build
#       --pull
#       --build-arg VCS_REF=staging
#       --build-arg VCS_URL=$CI_PROJECT_URL
#       --cache-from $CI_REGISTRY_IMAGE/app:staging
#       --tag $CI_REGISTRY_IMAGE/app:staging
#       .
#     - docker push $CI_REGISTRY_IMAGE/app:staging

