version: '3'
services:
  mongo:
    container_name: team_builder_mongo_dev
    image: mongo
    restart: always
    ports:
      - 27018:27018
    volumes:
      - mongodbdata:/data/db
    env_file:
      - .env.development
    command: mongod --port 27018
  server:
    container_name: team_builder_app_dev
    image: registry.gitlab.com/garneau-dev/sugoi/team-builder/app-dev:1.0.0
    restart: always
    ports:
      - 5001:5001
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    depends_on:
      - mongo
    env_file:
      - .env.development
    environment:
      WAIT_HOSTS: mongo:27018
  vue-dev:
    container_name: team_builder_frontend_dev
    image: registry.gitlab.com/garneau-dev/sugoi/team-builder/app-frontend-dev:1.0.0
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    depends_on:
      - server
    env_file:
      - .env.development
    environment:
      WAIT_HOSTS: server:5001
volumes:
  mongodbdata:
