version: "3"
services:
  server:
    container_name: team_builder_app
    image: registry.gitlab.com/garneau-dev/sugoi/kit-creator/app:0.1.0
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    env_file:
      - .env
    command: npm run dev
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    command: mongod --port 27018
    ports:
      - 27018:27018
volumes:
  mongodbdata:
