version: '3'
services:
  mongo:
    container_name: team_builder_mongo_dev
    image: mongo:4.0
    restart: always
    ports:
      - 27018:27018
    volumes:
      - mongodbdata:/data/db
    env_file:
      - .env.development
    command: mongod --port 27018
  server:
    container_name: team_builder_app_dev
    image: registry.gitlab.com/garneau-dev/sugoi/team-builder/app:develop
    restart: always
    ports:
      - 5001:5001
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    env_file:
      - .env.development
    environment:
      WAIT_HOSTS: mongo:27018
    command: npm run dev
volumes:
  mongodbdata:
