version: '3'
services:
  server:
    container_name: team_builder_app_dev
    image: registry.gitlab.com/garneau-dev/sugoi/team-builder/app:develop
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    # env_file:
    #   - .env.development
    command: npm run server-dev
